[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/RTradeLtd/go-ipfs-api"
  branch = "master"
 
[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "0.0.1"

[[constraint]]
  name = "github.com/RTradeLtd/entropy-mnemonics"
  branch = "master"